
###
GET http://localhost:9090

###
POST http://localhost:9090/auth/signup/ HTTP/1.1
content-type: application/json

{
    "fullName":"RaviSK",
    "email": "ravisharmacs09@gmail.com",
    "password": "ravics09"
}

###
POST http://localhost:9090/auth/signin/ HTTP/1.1
content-type: application/json

{
    "email": "ravisharmacs09@gmail.com",
    "password": "ravics09"
}

###
GET HTTP://localhost:9090/user

###
GET HTTP://localhost:9090/user/profile/624540ca4ac88651a691f99e HTTP/1.1
content-type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlzaGFybWFjczA5QGdtYWlsLmNvbSIsImlhdCI6MTY0ODc0MTEzMywiZXhwIjoxNjQ4ODI3NTMzfQ.9w9mGSALjMRxIS014hh0lugorOMq7qjH1rBUxxQOrpo


